/**
 * 定义应用路由
 */
import React from 'react';
import {
  Router,
  hashHistory,
} from 'react-router';
import { Provider } from 'react-redux';
import store from './store'

import HeaderAsideFooterLayout from './layouts/HeaderAsideFooterLayout';
import Dashboard from './pages/Dashboard';
import CateList from './pages/CateList';
import TagList from './pages/TagList';
import CreateTag from './pages/CreateTag';
import UserList from './pages/UserList';
import NotFound from './pages/NotFound';
const autoGeneratedRoutes = [
  {
    path: '/',
    childRoutes: [{
      path: 'list',
      childRoutes: [],
      component: TagList
    }, {
      path: 'create',
      childRoutes: [],
      component: CreateTag
    }],
    component: HeaderAsideFooterLayout,
    indexRoute: {
      component: TagList
    }
  },
  {
    path: '/mycurise',
    childRoutes: [],
    component: HeaderAsideFooterLayout,
    indexRoute: {
      component: UserList
    }
  },
  {
    path: '/help',
    childRoutes: [],
    component: HeaderAsideFooterLayout,
    indexRoute: {
      component: CateList
    }
  },
  {
    path: '/agent',
    childRoutes: [{
      path: '*',
      childRoutes: [],
      component: NotFound
    }],
    component: HeaderAsideFooterLayout,
    indexRoute: {
      component: Dashboard
    }
  }];

// 自定义路由，如果 path 相同则会覆盖自动生成部分的路由配置
const customRoutes = [];

export default (
  <Provider store={store}>
    <Router
      history={hashHistory}
      routes={[...autoGeneratedRoutes, ...customRoutes]}
    />
  </Provider>
);
